name: Java CI
on: [ push ]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Gradle Build Action
        uses: gradle/gradle-build-action@v2.3.1
        with:
          arguments: build
          build-root-directory: app


